Travis added missing semicolons

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -29,10 +29,10 @@ script:
       arduino --verify --board $BOARD $PWD/${d%/}/${d%/}.ino;
       if [ $? -ne 0 ]; then
         # example build failed
-        echo -e "\033[0;31m${d%/} build failed"
-        exit 1
+        echo -e "\033[0;31m${d%/} build failed";
+        exit 1;
       else
         # example build succeeded
-        echo -e "\033[0;32m${d%/} build passed"
+        echo -e "\033[0;32m${d%/} build passed";
       fi
     done
