Travis added exit

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -26,14 +26,13 @@ script:
   # build all example sketches
   - cd examples
   - for d in */ ; do
-      local status;
-      status = $(arduino --verify --board $BOARD $PWD/${d%/}/${d%/}.ino 2>&1);
+      local status = $(arduino --verify --board $BOARD $PWD/${d%/}/${d%/}.ino 2>&1)
       if [ $status -ne 0 ]; then
         # example build failed
-        echo -e "\033[0;31m${d%/} build failed";
-        return $status;
+        echo -e "\033[0;31m${d%/} build failed"
+        exit $status
       else
         # example build succeeded
-        echo -e "\033[0;32m${d%/} build passed";
+        echo -e "\033[0;32m${d%/} build passed"
       fi
     done
